"""empty message

Revision ID: 487dae868112
Revises: 6b9ece7d14d8
Create Date: 2022-03-11 00:57:40.592491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487dae868112'
down_revision = '6b9ece7d14d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('address', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'address')
    # ### end Alembic commands ###
