"""empty message

Revision ID: 737c6daadfd6
Revises: 
Create Date: 2022-02-21 20:05:58.238806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737c6daadfd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    # ### end Alembic commands ###
